; AUTO-GENERATED by tools/gen_world.py -- do not edit
.segment "BANK2"
.export Ts0Chr, Ts0ChrEnd, Ts0Pal, Ts0Meta, Ts0Attr, Ts1Chr, Ts1ChrEnd, Ts1Pal, Ts1Meta, Ts1Attr, Ts2Chr, Ts2ChrEnd, Ts2Pal, Ts2Meta, Ts2Attr, Ts3Chr, Ts3ChrEnd, Ts3Pal, Ts3Meta, Ts3Attr, Ts4Chr, Ts4ChrEnd, Ts4Pal, Ts4Meta, Ts4Attr
Ts0Chr:  .incbin "ts0_chr.bin"
Ts0ChrEnd:
Ts0Pal:  .incbin "ts0_pal.bin"
Ts0Meta: .incbin "ts0_meta.bin"
Ts0Attr: .incbin "ts0_attr.bin"
Ts1Chr:  .incbin "ts1_chr.bin"
Ts1ChrEnd:
Ts1Pal:  .incbin "ts1_pal.bin"
Ts1Meta: .incbin "ts1_meta.bin"
Ts1Attr: .incbin "ts1_attr.bin"
Ts2Chr:  .incbin "ts2_chr.bin"
Ts2ChrEnd:
Ts2Pal:  .incbin "ts2_pal.bin"
Ts2Meta: .incbin "ts2_meta.bin"
Ts2Attr: .incbin "ts2_attr.bin"
Ts3Chr:  .incbin "ts3_chr.bin"
Ts3ChrEnd:
Ts3Pal:  .incbin "ts3_pal.bin"
Ts3Meta: .incbin "ts3_meta.bin"
Ts3Attr: .incbin "ts3_attr.bin"
Ts4Chr:  .incbin "ts4_chr.bin"
Ts4ChrEnd:
Ts4Pal:  .incbin "ts4_pal.bin"
Ts4Meta: .incbin "ts4_meta.bin"
Ts4Attr: .incbin "ts4_attr.bin"
.segment "BANK3"
.export Map0
Map0: .incbin "map0.bin"
.export Map1
Map1: .incbin "map1.bin"
.export Map2
Map2: .incbin "map2.bin"
.segment "BANK4"
.export Map3
Map3: .incbin "map3.bin"
.export Map4
Map4: .incbin "map4.bin"
.export Map5
Map5: .incbin "map5.bin"
.segment "BANK5"
.export Map6
Map6: .incbin "map6.bin"
.export Map7
Map7: .incbin "map7.bin"
.export Map8
Map8: .incbin "map8.bin"
.segment "BANK7"
.export Map9
Map9: .incbin "map9.bin"
.segment "BANK8"
.export StoryTab
Str0: .byte "Miner:", 1, "The caverns below Lyra rumble.", 1, "Something huge stirs there...", 0
Str1: .byte "Carved above the arch:", 1, "HERE SLEEPS THE SHAPER", 1, "OF VALLEYS. DIG NOT DEEP.", 0
Str2: .byte "Found an Elixir!", 0
Str3: .byte "Found an Ether!", 0
Str4: .byte "Found a Hi-Potion!", 0
Str5: .byte "Found a Potion!", 0
Str6: .byte "Found a Revive!", 0
Str7: .byte "CHRONO WYRM:", 1, "*A serpent of pure paradox", 1, "coils through the void*", 0
Str8: .byte "The paradox dissolves!", 1, "The Rift feels calmer now.", 0
Str9: .byte "Flickering terminal:", 1, "...year 2300... Xethul event...", 1, "all cities lost... the Crystal", 1, "is our last power source...", 0
Str10: .byte "The time gate crackles...", 1, "The crystals' song pulls you", 1, "through the ages!", 0
Str11: .byte "GRASK, WARDEN OF TIDES:", 1, "WHO DARES CLAIM THE", 1, "WATER CRYSTAL?!", 0
Str12: .byte "The WATER CRYSTAL is yours!", 1, "Its light hums with the tide.", 0
Str13: .byte "A shard of crystal light", 1, "washes over the party.", 1, "HP and MP restored!", 0
Str14: .byte "Knight:", 1, "Fiends spill from the Crystal", 1, "Cave. Our blades cannot cut", 1, "their hides!", 0
Str15: .byte "MAGMADON:", 1, "*The volcano itself seems", 1, "to rise on ancient legs*", 0
Str16: .byte "The FIRE CRYSTAL is yours!", 1, "It burns without burning.", 0
Str17: .byte "The walls are made of eaten", 1, "centuries. Whispers of lost", 1, "timelines beg you onward.", 0
Str18: .byte "NIX:", 1, "...you can see me? In this", 1, "dead future, I thought I was", 1, "the last spark left.", 1, "NIX joined the party!", 0
Str19: .byte "OMEGA GOLEM:", 1, "PROTOTYPE X-9 ONLINE.", 1, "NO RECORDED DEFEATS.", 0
Str20: .byte "The ancient war machine", 1, "falls silent forever.", 0
Str21: .byte "Painted on a stone:", 1, "Big fire mountain. Angry.", 1, "Shiny stone inside.", 0
Str22: .byte "The four Crystals blaze!", 1, "The bridge of hours forms,", 1, "leading to Xethul's Maw!", 0
Str23: .byte "The bridge of hours is dark.", 1, "It needs the light of the", 1, "four Crystals.", 0
Str24: .byte "The Old Sage:", 1, "This is the Rift, outside time.", 1, "Xethul devours the Crystals.", 1, "Gather them: Water, Fire,", 1, "Wind, Earth. Then face it.", 0
Str25: .byte "LYRA CASTLE", 1, "Festival of Ages today!", 1, "The gate hums strangely...", 0
Str26: .byte "Old woman:", 1, "Legends say five Crystals keep", 1, "the ages turning in harmony.", 0
Str27: .byte "Boy:", 1, "A blue swirl took my kite!", 1, "It flew INTO the gate!", 0
Str28: .byte "Villager:", 1, "The old gate on the east hill", 1, "has begun to glow. Be careful!", 0
Str29: .byte "SLADE:", 1, "A mercenary fights for coin...", 1, "but time itself unraveling?", 1, "That one's on the house.", 1, "SLADE joined the party!", 0
Str30: .byte "STEEL WARDEN:", 1, "INTRUDERS DETECTED.", 1, "CRYSTAL VAULT SEALED.", 1, "TERMINATION COMMENCING.", 0
Str31: .byte "The WIND CRYSTAL is yours!", 1, "It whispers of open skies.", 0
Str32: .byte "WYLA:", 1, "You fight strong! Wyla fight", 1, "with you. Smash big lizard!", 1, "WYLA joined the party!", 0
Str33: .byte "TERRA WYRM:", 1, "*The caverns shake as the", 1, "great worm uncoils*", 0
Str34: .byte "The EARTH CRYSTAL is yours!", 1, "It is heavier than mountains.", 0
Str35: .byte "XETHUL, THE TIME EATER:", 1, "LITTLE SPARKS OF HISTORY...", 1, "I HAVE EATEN A THOUSAND", 1, "TIMELINES. YOURS IS NEXT.", 0
StoryTab:
  .faraddr Str0
  .faraddr Str1
  .faraddr Str2
  .faraddr Str3
  .faraddr Str4
  .faraddr Str5
  .faraddr Str6
  .faraddr Str7
  .faraddr Str8
  .faraddr Str9
  .faraddr Str10
  .faraddr Str11
  .faraddr Str12
  .faraddr Str13
  .faraddr Str14
  .faraddr Str15
  .faraddr Str16
  .faraddr Str17
  .faraddr Str18
  .faraddr Str19
  .faraddr Str20
  .faraddr Str21
  .faraddr Str22
  .faraddr Str23
  .faraddr Str24
  .faraddr Str25
  .faraddr Str26
  .faraddr Str27
  .faraddr Str28
  .faraddr Str29
  .faraddr Str30
  .faraddr Str31
  .faraddr Str32
  .faraddr Str33
  .faraddr Str34
  .faraddr Str35
.segment "RODATA"
.export MapTable, TsChrTable, TsChrSize, TsPalTable, TsMetaTable, TsAttrTable
.export TsGroundMeta, TsHedgeMeta
MapTable: .faraddr Map0
  .faraddr Map1
  .faraddr Map2
  .faraddr Map3
  .faraddr Map4
  .faraddr Map5
  .faraddr Map6
  .faraddr Map7
  .faraddr Map8
  .faraddr Map9
TsChrTable:
  .faraddr Ts0Chr
  .faraddr Ts1Chr
  .faraddr Ts2Chr
  .faraddr Ts3Chr
  .faraddr Ts4Chr
TsChrSize:
  .word Ts0ChrEnd-Ts0Chr
  .word Ts1ChrEnd-Ts1Chr
  .word Ts2ChrEnd-Ts2Chr
  .word Ts3ChrEnd-Ts3Chr
  .word Ts4ChrEnd-Ts4Chr
TsPalTable:
  .faraddr Ts0Pal
  .faraddr Ts1Pal
  .faraddr Ts2Pal
  .faraddr Ts3Pal
  .faraddr Ts4Pal
TsMetaTable:
  .faraddr Ts0Meta
  .faraddr Ts1Meta
  .faraddr Ts2Meta
  .faraddr Ts3Meta
  .faraddr Ts4Meta
TsAttrTable:
  .faraddr Ts0Attr
  .faraddr Ts1Attr
  .faraddr Ts2Attr
  .faraddr Ts3Attr
  .faraddr Ts4Attr
TsGroundMeta: .byte 2, 2, 2, 2, 2
TsHedgeMeta:  .byte 10, 8, 6, 6, 0
