; AUTO-GENERATED by tools/gen_world.py -- do not edit
.segment "BANK2"
.export Ts0Chr, Ts0ChrEnd, Ts0Pal, Ts0Meta, Ts0Attr
Ts0Chr:  .incbin "ts0_chr.bin"
Ts0ChrEnd:
Ts0Pal:  .incbin "ts0_pal.bin"
Ts0Meta: .incbin "ts0_meta.bin"
Ts0Attr: .incbin "ts0_attr.bin"

.segment "BANK3"
.export Map0
Map0:    .incbin "map0.bin"

.segment "RODATA"
.export MapTable, TsChrTable, TsChrSize, TsPalTable, TsMetaTable, TsAttrTable
MapTable:    .faraddr Map0
TsChrTable:  .faraddr Ts0Chr
TsChrSize:   .word Ts0ChrEnd-Ts0Chr
TsPalTable:  .faraddr Ts0Pal
TsMetaTable: .faraddr Ts0Meta
TsAttrTable: .faraddr Ts0Attr
